// <auto-generated />
using CatalogoITT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatalogoITT.Migrations
{
    [DbContext(typeof(LibroContext))]
    partial class LibroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CatalogoITT.Models.Libro", b =>
                {
                    b.Property<int>("libro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("anio_publicacion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("autor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("clasificacion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("edicion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("editorial")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("isbn")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("paginas")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("registro_en_siabuk")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("reserva")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("libro_id");

                    b.ToTable("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
